### PR TITLE
feat(react): add eslint plugin to lint react/jsx specific styles

### PR DESCRIPTION
**Pull request by jwarning**
Add rules to make sure eslint checks that React has been included when JSX is used.

### CODE REVIEW

**Comment by chasevida** [comment]
Hey this looks cool. Do you want to run `npm run docs` to update the README too? This isn't controversial so I'm happy to merge it if there are no objections from others?

/cc @colensobbdo/core

**Comment by jwarning** [comment]
Sweet, yeah already forgot that haha.

**Comment by chasevida** [comment]
I'm cool with this, just need one more vote. @logikaljay @minigopher17 ?

**Comment by logikaljay** [comment]
Sounds good!

**Pull request merged**
