### PR TITLE
Change code indent to 2 spaces

### PR DESCRIPTION
**Pull request by chasevida**
Totally controversial but how'd people feel about going down to 2 spaces for an indent? 

I think when we were using 4 spaces we had a lot of people still getting comfortable with `js` programming and the visual space was really helpful at that time. However, I think we can help people out who struggle with things like that by setting up their editor/IDE to give extra visual spacing with padding etc.

/cc @colensobbdo/core

### CODE REVIEW

**Comment by logikaljay** [comment]
Sorry, I really do prefer 4 spaces.

**Comment by chasevida** [comment]
Ok, happy to stick with 4 - I imagine the Spark team probably prefers it too.

**Comment by jwarning** [comment]
Do we close this for now then?

**Comment by chasevida** [comment]
Do people want to try it for a day or two and see how they feel? I had always preferred 4 spaces but after trying 2 out for a while found it fine. But yeah, spose we should close it then.

**Pull request closed without merging**
